Statusline for neovim 0.10
NvChad/ui pull request #189
Opened 2023-09-29 15:11 UTC by carlobonandriniunimi

Modified statusline lsp progress and servers to work with neovim 0.10

2023-09-29 15:19 UTC, lucario387 commented on lua/nvchad/statusline/minimal.lua
> +  if not rawget(vim, "lsp") or vim.o.columns < 120 or not status then
don't think rawget(vim, "lsp") is really needed nowadays

2023-09-29 15:30 UTC, siduck commented
I'm not willing to support lsp progress for v0.10 until v0.10 becomes the latest stable release. For the time being, just override statusline module

2023-09-29 15:32 UTC, carlobonandriniunimi commented
> I'm not willing to support lsp progress for v0.10 until v0.10 becomes the latest stable release. For the time being, just override statusline module

Yeah that’s what I did, I just thought it would be useful for anyone who uses nightly like me. Close the issue if you don’t need it

2023-09-29 15:35 UTC, carlobonandriniunimi commented
I did a rework on how the lsp progress icon is displayed using the percentage instead of the current time, thought it was more intuitive

2023-09-29 15:35 UTC, siduck commented
> > I'm not willing to support lsp progress for v0.10 until v0.10 becomes the latest stable release. For the time being, just override statusline module
> 
> Yeah that’s what I did, I just thought it would be useful for anyone who uses nightly like me. Close the issue if you don’t need it

no reason to close it. It'll just be open until v0.10 releases, I'll merge this

2023-09-29 15:37 UTC, carlobonandriniunimi commented
> > > I'm not willing to support lsp progress for v0.10 until v0.10 becomes the latest stable release. For the time being, just override statusline module
> > 
> > 
> > Yeah that’s what I did, I just thought it would be useful for anyone who uses nightly like me. Close the issue if you don’t need it
> 
> no reason to close it. It'll just be open until v0.10 releases, I'll merge this

So is v3.0 scheduled to be on 0.9 or where you thinking of releasing it when 0.10 is out?

2023-09-29 15:42 UTC, siduck commented
> > > > I'm not willing to support lsp progress for v0.10 until v0.10 becomes the latest stable release. For the time being, just override statusline module
> > > 
> > > 
> > > Yeah that’s what I did, I just thought it would be useful for anyone who uses nightly like me. Close the issue if you don’t need it
> > 
> > 
> > no reason to close it. It'll just be open until v0.10 releases, I'll merge this
> 
> So is v3.0 scheduled to be on 0.9 or where you thinking of releasing it when 0.10 is out?

New releases in nvchad have new features. So its not really tied to nvim versions. And this PR isnt a feature, it just updates the nvim api of doing things.

2023-10-10 14:09 UTC, lucario387 commented on lua/nvchad/statusline/default.lua
> +  local status = utils.get_message()
what is this get_message() or am I clueless

2023-10-10 14:12 UTC, yoplat commented on lua/nvchad/statusline/default.lua
> +  local status = utils.get_message()
> what is this get_message() or am I clueless

Added it to utils.lua file, I don’t think there is a way to get the progress message like before so I created a similar function

2023-10-10 14:23 UTC, lucario387 commented on lua/nvchad/statusline/default.lua
> +  local status = utils.get_message()
So where's the get_message for NvChad then? Because rn I don't see any branch with that function

2023-10-10 14:27 UTC, yoplat commented on lua/nvchad/statusline/default.lua
> +  local status = utils.get_message()
<img width="1820" alt="Screenshot 2023-10-10 at 16 26 18" src="https://github.com/NvChad/ui/assets/98645146/6e7944cc-4905-4c63-bd31-b151d7b48e18">

Are you sure? This is what I see

2023-10-10 14:36 UTC, lucario387 commented on lua/nvchad/statusline/default.lua
> +  local status = utils.get_message()
All I see is that you are having `local utils = require ("core.utils")` and then using `utils.get_message`, which leads to the question of where that function actually lies

2023-10-10 14:46 UTC, yoplat commented on lua/nvchad/statusline/default.lua
> +  local status = utils.get_message()
> All I see is that you are having `local utils = require ("core.utils")` and then using `utils.get_message`, which leads to the question of where that function actually lies

I seriously don't know what to tell you, I see the file in the "files changed" tab in github and in lua/nvchad/utils.lua there is the get_message function

2023-10-10 14:48 UTC, yoplat commented on lua/nvchad/statusline/default.lua
> +  local status = utils.get_message()
I'm not that used to pull requests so I might have made something wrong, I merged the current v3.0 branch and the utils.lua file still contains the function

2023-10-10 14:52 UTC, lucario387 commented on lua/nvchad/statusline/default.lua
> +  local status = utils.get_message()
You are not requiring nvchad/utils.lua file from what I can see

```lua
local utils = require("core.utils") 
```
means utils is the returned module from `lua/core/utils.lua`, not `lua/nvchad/utils.lua`

2023-10-10 14:54 UTC, yoplat commented on lua/nvchad/statusline/default.lua
> +  local status = utils.get_message()
> You are not requiring nvchad/utils.lua file from what I can see
> 
> ```lua
> local utils = require("core.utils") 
> ```
> 
> means utils is the returned module from `lua/core/utils.lua`, not `lua/nvchad/utils.lua`

Whooops! Now I get it. Fixing it right now thanks

2023-10-10 15:03 UTC, lucario387 requested changes

2023-10-10 15:03 UTC, lucario387 commented on lua/nvchad/statusline/default.lua
> +  local status = require("utils").get_message()
Wrong
```suggestion
  local status = require("nvchad.utils").get_message()
```

2023-10-10 15:07 UTC, yoplat commented on lua/nvchad/statusline/default.lua
> +  local status = require("utils").get_message()
I'm stupid lol

2023-10-10 15:10 UTC, lucario387 approved these changes

2024-02-11 07:14 UTC, closed without merging